site_name: Data Science Template
site_description: A project template and directory structure for Python data science projects.
site_favicon: favicon.ico
repo_url: https://github.com/RMeissnerCC/datascience_template
edit_uri: edit/master/docs/docs
copyright: Fork of https://github.com/drivendata/cookiecutter-data-science, Maintained by me
google_analytics: ['UA-54096005-4', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
